version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8333:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  radiator:
    build: .
    ports:
      - "8100:80"
    environment: 
      - JENKINS_HOST=http://jenkins:8080
volumes:
  jenkins_home:   
    name: jenkins_home  